### PR TITLE
Add option "defaultInput" to all keyIn* methods

### PR DESCRIPTION
**Pull request by dstroynov**
I found a lack of option 'defaultInput' in all KeyIn* methods and improved it. It works fine for all four methods, even for keyInSelect. Notice that default input is marked in all methods (except for keyInPause)

### CODE REVIEW

**Comment by anseki** [comment]
Hi @dstroynov, thank you for your PR.

So, I can't yet understand this PR. When you want to use `defaultInput` option for `keyIn*` methods?
`defaultInput` option is used when user input **nothing**.
`keyIn*` methods don't return until user input a **key**.
That is, `defaultInput` option is never used for `keyIn*` methods.

Therefore, I deliberately excluded `defaultInput` option from `keyIn*` methods, this is not lack.

Or, do you want to override a pressed key with another value?

**Comment by dstroynov** [comment]
If I understood it properly, defaultInput is used when user pressed Enter and put nothing as an answer (for question* methods). In this case default value will be returned.
I would like to get the same functionality for keyIn* methods. May be it's better to call it "recommended" input, because it's a value that will be returned if a user hit Enter instead of one of allowed keys.

For example, I've got a question:
```js
readlineSync.keyInYNStrict("Do you want to do this?")
```
In this case user will see
```console
Do you want to do this? [y/n] :
```
and he must decide if he wants to use it or not.

If I will use default input
```js
readlineSync.keyInYNStrict("Do you want to do this?", { defaultInput: "Y" })
```
then user will see
```console
Do you want to do this? [Y/n] :
```
and now it's not needed for him to decide does he want it or not, a user could just hit Enter and the default (recommended) value will be returned (Notice the uppercase "Y" in a guide). 

And probably, it'll even more useful for keyInSelect:
```js
readlineSync.keyInYNStrict(
  ["once an hour", "once a day", "once a week", "once a month", "once a year"],
  "How often do you want do do this?",
  { defaultInput: 3 }
)
```

```console
 [1] once an hour
 [2] once a day
*[3] once a week
 [4] once a month
 [5] once a year
 [0] CANCEL

How often do you want do do this? [1..5 / 0] :
```
And now it's obvious for user, that if he doesn't want to decide how often he wants to do this, he could hit Enter and select recommended value - once a week.

**Comment by anseki** [comment]
You seem to have misunderstood `keyIn*` methods.
See: https://github.com/anseki/readline-sync#keyin
With `keyIn*` methods, user replies by pressing single key without Enter key.
Therefore your PR didn't work. Of course I tried that.

[`keyInYN` method](https://github.com/anseki/readline-sync#keyinyn) (not `keyInYNStrict`) that supports default choice may help you.
You can decide "Yes" or "No" when user did not it. (See example in doc above)

`keyInYNStrict` method is used instead of `keyInYN` method to make user answer it clearly (`Strict` means it). That is, it is used to deny unclear replying by user. Then, it should not implement the default. Use `keyInYN` method instead if you want default.

`keyInSelect` supports `cancel` option to allow user to not decide.
For example, make first item in `items` Array be default:
```js
{cancel: '$<firstItem> (recommend)'}
```

**Comment by dstroynov** [comment]
I hope I understood keyIN* properly. 
But I thought Enter is a key as well (of course, it's a special key).

That's why when you { defaultInput : "Y" }  for keyInYNStrict, I want user to do one of the following actions:
- Press "Y"  without pressing Enter
- Press "N" without pressing Enter
- Press "Enter" once and select predefined default value
All other keys are not processed.

I thought, this feature could be useful in a case if we got a long list of questions and a user doesn't want to think on every question and wants to pass through it quickly.

**Comment by anseki** [comment]
Thank you for your proposal.
Current readlineSync deliberately ignore control characters.
When I found certain way to get those in any environment, I will examine implementation in future version.
(But, your idea suits `keyInYN` method. **Not `keyInYNStrict` method.** As I said, `keyInYNStrict` method is used to deny unclear replying. Therefore if `keyInYNStrict` method supports default value, nobody uses `keyInYNStrict` method.)

BTW, a message for users that don't want to think should be contained to `query`.
I made `keyInSelect` show `query` after `items` for long list. User who don't want to think will see `query` without reading a long list even if a screen was scrolled by long list.

**Comment by anseki** [comment]
And also, note that user has no chance to change the input. (See doc.)
When you want to  let user choose something, the default might be unintended behavior.
`question*` or `prompt*` methods may be better in your case.

**Comment by anseki** [comment]
No reply came, and I close this PR.
And, sorry, I could not merge the PR because the script you customized did not work.
At least, you should make sure that your PR works before you send it to any repository. This is important process to make it be able to be merged.
Thank you again for your time :smile:

**Pull request closed without merging**
