### PR TITLE
Don't git include all the useless files.

### PR DESCRIPTION
**Pull request by paulmillr**
Only lib is necessary.

### CODE REVIEW

**Comment by anseki** [comment]
Thank you! 😄

**Comment by paulmillr** [comment]
Please release a new version @anseki

**Comment by anseki** [comment]
Is something the matter?
Do you need that right now?

**Comment by paulmillr** [comment]
Yes, we need it ASAP to decrease our build size.

**Comment by anseki** [comment]
Ok, I'll release a new version after.

**Comment by anseki** [comment]
v1.4.8 was released.

**Pull request merged**
